Release 2.2.0
voxpupuli/voxpupuli-acceptance pull request #68
Opened 2023-09-20 10:20 UTC by bastelfreak

2023-09-20 10:28 UTC, ekohl approved these changes

2023-09-20 10:30 UTC, ekohl requested changes
@evgeni pointed out something was breaking: https://github.com/voxpupuli/voxpupuli-acceptance/pull/59/files#r1331418468

Let's fix that up to not be breaking.

2023-10-16 14:03 UTC, ekohl requested changes
And now I also want https://github.com/voxpupuli/voxpupuli-acceptance/pull/70.

2023-10-17 22:48 UTC, ekohl commented
Please update, I'd like to have Fedora/Debian non-AIO testing support :)

2023-10-18 08:05 UTC, tuxmea approved these changes

2023-10-18 08:08 UTC, merged